/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "RST_aliases.h"
#include "RST.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "LCD.h"
#include "blue_aliases.h"
#include "blue.h"
#include "pink_aliases.h"
#include "pink.h"
#include "yellow_aliases.h"
#include "yellow.h"
#include "orange_aliases.h"
#include "orange.h"
#include "ADC.h"
#include "Ain_aliases.h"
#include "Ain.h"
#include "Opamp.h"
#include "switch3_aliases.h"
#include "switch3.h"
#include "UART.h"
#include "DAC.h"
#include "DACpin_aliases.h"
#include "DACpin.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

